### PR TITLE
Reworked camera system

### PR DESCRIPTION
**Pull request by kyle-robinson**
Reworked the camera system to allow for independent movement of the player, and the ability to lock to the player's position.

Also added options to change the camera's movement speed and width/height scale.

https://user-images.githubusercontent.com/39779606/214902749-2cc234f7-4b4c-4ff1-bb50-cbc88b962564.mp4

### CODE REVIEW

**Review by juliusz-kaczmarek — CHANGES_REQUESTED** [review]
View size sliders are bugged (they reset to default values, although it keeps changes).
Can you take a look again on it Kyle?

**Comment by kyle-robinson** [comment]
> View size sliders are bugged (they reset to default values, although it keeps changes). Can you take a look again on it Kyle?

Just removed the ability change the camera view width/height. Realised that this is kind of irrelevant.

**Review by juliusz-kaczmarek — APPROVED** [review]

**Comment by juliusz-kaczmarek** [comment]
Locking to a player doesnt seem to work, something with player entity seems to be bugged either, as I can't move the players with  WSAD keys (it's as if player tag isnt correctly applied to entity?)

**Comment by kyle-robinson** [comment]
> Locking to a player doesnt seem to work, something with player entity seems to be bugged either, as I can't move the players with WSAD keys (it's as if player tag isnt correctly applied to entity?)

Will take a look at this, and see what the issue is.

**Comment by kyle-robinson** [comment]
> Locking to a player doesnt seem to work, something with player entity seems to be bugged either, as I can't move the players with WSAD keys (it's as if player tag isnt correctly applied to entity?)

Seems to be related to the entity editor and the changes that were made to it recently. With regard to this though, everything seems to be working fine. I think because Charlie was refactoring the entity code explains why WASD doesn't do anything atm.

**Pull request merged**
